# Bakes maps/*.txt into a C++ source so the built binary needs no data files
# beside it. Run at build time, so an edited or added map cannot drift from what
# ships inside the executable.
#
# The payload is emitted as a byte array rather than a string literal on
# purpose: MSVC caps a single string literal at 65535 bytes and de_dust2 is ten
# times that, so the obvious R"(...)" form builds on GCC and fails on MSVC.
#
# Expects MAPS_DIR and OUTPUT on the command line.

file(GLOB map_files "${MAPS_DIR}/*.txt")
list(SORT map_files)

set(body "")
set(table "")
set(count 0)

foreach(map_file ${map_files})
  get_filename_component(map_name "${map_file}" NAME)
  file(READ "${map_file}" hex HEX)
  string(LENGTH "${hex}" hex_len)
  math(EXPR byte_len "${hex_len} / 2")

  # "0a1b" -> "0x0a,0x1b,", then a newline every 16 bytes so the generated file
  # is still openable in an editor. CMake's regex has no {n} repetition, so the
  # sixteen groups are spelled out.
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  set(sixteen "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)")
  string(REGEX REPLACE "${sixteen}" "\\1\n" bytes "${bytes}")

  string(APPEND body "static const unsigned char kMap${count}[] = {\n${bytes}\n0x00};\n\n")
  string(APPEND table "    {\"${map_name}\", reinterpret_cast<const char*>(kMap${count}), ${byte_len}},\n")
  math(EXPR count "${count} + 1")
endforeach()

set(generated "// Generated by cmake/embed_maps.cmake. Do not edit.\n")
string(APPEND generated "//\n// Every map under maps/ is baked in here so the executable is the only file\n")
string(APPEND generated "// needed to run the game. map_load() reads from disk first and falls back to\n")
string(APPEND generated "// these, so an edited map on disk still wins during development.\n\n")
string(APPEND generated "#include \"game/embedded_maps.h\"\n\n#include <cstring>\n\n")
string(APPEND generated "namespace {\n\n${body}")
string(APPEND generated "struct EmbeddedMap {\n  const char* name;\n  const char* text;\n  int size;\n};\n\n")
string(APPEND generated "const EmbeddedMap kMaps[] = {\n${table}};\n\n")
string(APPEND generated "// Basename of a path, so \"maps/x.txt\", \"./maps/x.txt\" and \"x.txt\" all match.\n")
string(APPEND generated "const char* basename_of(const char* path) {\n")
string(APPEND generated "  const char* last = path;\n")
string(APPEND generated "  for (const char* p = path; *p; ++p) {\n")
string(APPEND generated "    if (*p == '/' || *p == '\\\\') last = p + 1;\n  }\n  return last;\n}\n\n")
string(APPEND generated "}  // namespace\n\n")
string(APPEND generated "const char* embedded_map_text(const char* path, int* size_out) {\n")
string(APPEND generated "  if (!path) return nullptr;\n")
string(APPEND generated "  const char* name = basename_of(path);\n")
string(APPEND generated "  for (const EmbeddedMap& m : kMaps) {\n")
string(APPEND generated "    if (std::strcmp(m.name, name) == 0) {\n")
string(APPEND generated "      if (size_out) *size_out = m.size;\n      return m.text;\n    }\n  }\n")
string(APPEND generated "  return nullptr;\n}\n\n")
string(APPEND generated "int embedded_map_count() {\n  return ${count};\n}\n\n")
string(APPEND generated "const char* embedded_map_name(int index) {\n")
string(APPEND generated "  if (index < 0 || index >= ${count}) return nullptr;\n")
string(APPEND generated "  return kMaps[index].name;\n}\n")

# Only rewrite when the contents actually change, so touching a map that did not
# change does not force a rebuild of everything downstream.
set(previous "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL generated)
  file(WRITE "${OUTPUT}" "${generated}")
  message(STATUS "embedded ${count} map(s) into ${OUTPUT}")
endif()
